"""Experimental data input/output handler functions."""
# TODO Uncertainty
from collections import namedtuple
import os
from os.path import join
import pdb
import sympy as sym
from sympy.core.sympify import SympifyError

import pandas as pd

from .label_handler import translate_keys
from .unit import parse_unit_string
from .compat import (casefold, filter, isdecimal, isidentifier)
from .frames import monkey_patch
from .unit import parse_unit_string
from .uncer_cal import eval_uncer

monkey_patch()


def load(filepath='./', ext='.htf', **kwargs):
    """Load a collection of test data and return data frames.

    This function provides an convenient method of loading a batch of
    test data collected for a system. For instance, if multiple test
    conditions were tested, this function returns the raw data for each
    test as well as a summary of all the test conditions.

    Parameters
    ----------
    filepath : str, optional
        Directory containing experimental data files. Default is cwd.
    ext : str, optional
        Test file extension to load. Default is '.htf'.

    Returns
    -------
    data : dict(pandas DataFrame)
        Dictionary of all the data in each test file read in as pandas
        data frames.
    summary : pandas DataFrame
        Data frame containing a summary of the data in each test file
        where each row corresponds to a single test. The summary data
        frame is generated by finding the means of each column in every
        test file.

    """

    # Make a temporary function used to filter only the test files.
    is_ext = lambda s: True if s.endswith(ext) else False

    # Read in each candidate file and give it a unique identifier.
    for root, _, files in os.walk(filepath):
        filtered = enumerate(filter(is_ext, sorted(files)))
        data = {ind: read(join(root, f), **kwargs) for ind, f in filtered}

    # Create the summary data frame from the raw data dictionary.
    summary = pd.DataFrame(
        data={name: item.mean() for name, item in data.items()}
    ).T

    # Need to append metadata info to new summary data frame.
    summary._metadata = list(set(summary._metadata))
    summary._units = {}
    summary._descriptions = {}
    for key in summary.keys():
        summary[key]._units = data[0][key]._units
    for id_, _ in summary.iterrows():
        summary._units.update(data[id_]._units)
        summary._descriptions.update(data[id_]._descriptions)
        for section, metadata in data[id_].metadata.items():
            for key, info in metadata.items():
                if key in summary.keys():
                    summary[key][id_], summary[key]._units = info
                else:
                    summary[key] = info.value
                    summary[key]._units = info.unit

    return data, summary


def read(filepath_or_buffer, header=0, units=1, **kwargs):
    """Read experimental data into pandas DataFrame.

    Parameters
    ----------
    filepath_or_buffer : string or file handle / StringIO.

    header : int
        Row to use for the column labels of the parsed DataFrame.
    units : int
        Row to use for the unit properties of the parsed DataFrame.

    Returns
    -------
    result : pandas DataFrame

    """

    with open(filepath_or_buffer, 'r') as f:
        metadata = parse_metadata(f)
        result = parse_raw_data(f, parse_dates=True, **kwargs)

    cleanse_uncer(result, metadata)
    result = append_metadata(result, metadata)

    # Currently, pandas only copies attributes that are added to
    # _metadata when it is copied.  Since pandas actually copies
    # frames frequently, this is a problem. To get around this, use
    # monkey-patching to store frame attributes and methods.

    result._metadata.append('_units')  # unit dictionary
    result._metadata.append('_descriptions')  # description dictionary
    result._metadata = list(set(result._metadata))

    # TO DO: only add _descriptions to the main data pandas Dataframe but not
    # the others
    result.__dict__[metadata.keys()[0]]._metadata.remove('_descriptions')

    return result


def parse_metadata(handle):
    """Parse test data file header metadata.

    Parameters
    ----------
    handle : test data file handle

    Returns
    -------
    metadata : dict
        parsed metadata dictionary describing test procedure

    """

    MetadataInfo = namedtuple('MetadataInfo', ['value', 'unit'])
    Uncertainty = namedtuple('Uncertainty', ['var', 'eqn'])

    metadata = {}
    while True:
        line = handle.readline().strip(' ;\n')
        if line.startswith('[raw data]'):
            return metadata
        elif line.startswith('[') and line.endswith(']'):
            section = cleanse_names(line.strip().strip('[]'))
            metadata[section] = {}
        else:
            key, info = [item.strip() for item in line.split('=')]
            if section == 'uncertainty':
                metadata[section][key] = Uncertainty(
                    *parse_uncertainty_data(key, info)
                )
            else:
                key = cleanse_names(key)
                value, unit = parse_metadata_info(info)
                metadata[section][key] = MetadataInfo(
                    *parse_metadata_info(info)
                )


def parse_metadata_info(info):
    """Parse floating point metadata info.

    Parameters
    ----------
    info : string

    Returns
    -------
    value : float
    unit : string

    """
    value, _, unit = [item.strip() for item in info.partition('[')]
    unit = unit.strip('[]') if unit else None

    # TODO Not happy with this code, don't like logic trees in general.
    # Also, I think there is many oppurtunities for Exceptions, should
    # make this more robust.
    if unit:
        if casefold(unit) == 'bool':
            value = True if casefold(value) == 'true' else False
        elif value.isdigit():
            value = int(value)
        elif isdecimal(value.replace('.', '')):
            unit = parse_unit_string(unit)
            value = float(value)

    return value, unit


def parse_uncertainty_data(key, info):
    """Parse test data file uncertainty information string

    Parameters
    ----------
    key   : string
        name of the variable of which the uncertainty information is stored in
        info
    info  : string
        rest of the information, including other variables in the uncertainty
        equation and the equation itself

    Returns
    -------
    var   : list of string
        names of variables
    eqn   : sympy expressions
        mathematical expressions or values of uncertainties, in which
        variables are represented by x0, x1, x2, etc.

    """

    if info.rfind('}') > 0:
        var, _, eqn = [item.strip() for item in info.partition('}')]
        var = [key]+[item.strip('{} ') for item in var.split(',')]
        eqn = eqn.strip()
    else:
        var = [key]
        eqn = info.strip()

    if len(eqn) == 0:  # assume zero uncertainty
        eqn = 0.

    try:
        eqn = sym.sympify(eqn)
    except SympifyError:
        print('Cannot convert '+eqn+' into Sympy expressions')
        eqn = sym.sympify('nan')

    return var, eqn


def parse_raw_data(handle, **kwargs):
    """Parse raw data from test output data file.

    Parameters
    ----------
    handle : test data file handle

    Returns
    -------
    result : pandas DataFrame

    """

    read_col_metadata = lambda line: line.strip().split(',')[1:]

    column_names = cleanse_names(read_col_metadata(handle.readline()))
    column_units = read_col_metadata(handle.readline())
    result = pd.read_csv(handle, names=column_names, **kwargs)

    # TODO It would be cool if key-unit pairs were methods that updated
    # with each call.
    for key, unit in zip(result.keys(), column_units):
        result[key]._units = parse_unit_string(unit)
    result._units = {key: result[key]._units for key in result.keys()}

    result = translate_keys(result, result.keys())
    result._descriptions = {
        key: result[key]._descriptions for key in result.keys()
    }

    return result


def cleanse_uncer(data, metadata):
    """Cleanse the uncertainty information by
        passing the original unit information
        set the uncertainty values which is absent in the information as zero

    Parameters
    ----------
    data : pandas DataFrame
        measurement DataFrame associated with metadata.
    metadata : dict
        metadata dictionary usually parsed from test data file header.

    Returns
    -------
    metadata : dict
        metadata dictionary usually parsed from test data file header.

    """

    UncertaintyInfo = namedtuple('UncertaintyInfo', ['var', 'eqn', 'ori_unit'])

    def _zero_uncertainty(key):
        return UncertaintyInfo([key], sym.sympify(0.), [data[key]._units])

    if 'uncertainty' in metadata.keys():
        # check if uncertainty info exists for the variables
        for key in data.keys():
            if key not in metadata['uncertainty']:  # set zero uncertainty
                metadata['uncertainty'][key] = _zero_uncertainty(key)
            else:  # add the unit information to UncertaintyInfo
                info = metadata['uncertainty'][key]
                unit = []
                var = []
                for name in info.var:
                    unit.append(data[name]._units)
                    var.append(name)
                metadata['uncertainty'][key] = \
                    UncertaintyInfo(var, info.eqn, unit)
    else:
        metadata['uncertainty'] = {}
        for key in data.keys():
            metadata['uncertainty'][key] = _zero_uncertainty(key)


def cleanse_names(names, bad_chars=[], repl='_'):
    """Cleanse a list of proposed column names to correct format.

    Parameters
    ----------
    names : string or [string]
        A string or list of proposed DataFrame column name strings
        usually read from test data file raw data header or metadata
        information.
    bad_chars : [string]
        List of invalid or bad characters that should be replaced from
        name strings if present
    repl : string
        String replacement for bad characters in cleansed name strings.

    Returns
    -------
    result : string or [string]
        String or list of cleansed DataFrame column names.

    Examples
    >>> cleanse_names(['a b c d', 'e_f g_i', 'j_k'])
    ['a_b_c_d', 'e_f_g_i', 'j_k']

    >>> cleanse_names(['1abc0'], repl='_')
    ['_abc0']

    >>> cleanse_names(' xxx')
    '_xxx'

    >>> cleanse_names('abcdef')
    'abcdef'

    """

    clean = lambda x, y: x + y if isidentifier(x + y) else x + repl

    result = ''
    if isinstance(names, str):
        for char in names:
            result = clean(result, char)
    else:
        result = [result] * len(names)
        for ind, name in enumerate(names):
            for char in name:
                result[ind] = clean(result[ind], char)

    return result


def append_metadata(data, metadata):
    """Append metadata information to the measurement DataFrame.

    Parameters
    ----------
    data : pandas DataFrame
        measurement DataFrame associated with metadata.
    metadata : dict
        metadata dictionary usually parsed from test data file header.

    Returns
    -------
    result : pandas DataFrame
        measurement DataFrame containing additional metadata properties.

    """

    data.metadata = metadata
    for section, meta in metadata.items():
        if section == 'uncertainty':
            data.__dict__[section] = pd.DataFrame(
                data={key: eval_uncer(
                    key, data, info
                ) for key, info in meta.items()},
                index=data.index
            )
            for key, info in meta.items():
                if data[key]._units.dimensionality.__str__() != \
                        '[temperature]':
                    data.__dict__[section][key]._units = data[key]._units
                else:
                    # change to temperature difference
                    data.__dict__[section][key]._units = parse_unit_string(
                        'delta_'+data[key]._units.units.__str__()
                    )
        else:
            data.__dict__[section] = pd.DataFrame(
                {key: [info.value] for key, info in meta.items()}
            )
            for key, info in meta.items():
                data.__dict__[section][key]._units = info.unit

        # setting unit dictionary
        data.__dict__[section]._units = {
            key: data.__dict__[section][key]._units
            for key in data.__dict__[section].keys()
        }

    return data
