# -*- coding: utf-8 -*-
"""Experimental data input/output handler functions."""
from collections import namedtuple
import os
from os.path import join

import pandas as pd

from .compat import (casefold, filter, isdecimal, isidentifier)
from .label_handler import translate_keys
from .uncertainty import parse_uncertainty_info
from .unit import parse_unit_string


def load(filepath='./', ext='.htf', **kwargs):
    """Load a collection of test data and return data frames.

    This function provides an convenient method of loading a batch of
    test data collected for a system. For instance, if multiple test
    conditions were tested, this function returns the raw data for each
    test as well as a summary of all the test conditions.

    Parameters
    ----------
    filepath : str, optional
        Directory containing experimental data files. Default is cwd.
    ext : str, optional
        Test file extension to load. Default is '.htf'.

    Returns
    -------
    data : dict(pandas DataFrame)
        Dictionary of all the data in each test file read in as pandas
        data frames.
    summary : pandas DataFrame
        Data frame containing a summary of the data in each test file
        where each row corresponds to a single test. The summary data
        frame is generated by finding the means of each column in every
        test file.

    """

    # Make a temporary function used to filter only the test files.
    is_ext = lambda s: True if s.endswith(ext) else False

    # Read in each candidate file and give it a unique identifier.
    for root, _, files in os.walk(filepath):
        filtered = enumerate(filter(is_ext, sorted(files)))
        data = {ind: read(join(root, f), **kwargs) for ind, f in filtered}

    # Create the summary data frame from the raw data dictionary.
    summary = pd.DataFrame(
        data={name: item.mean() for name, item in data.items()}
    ).T

    # Need to append metadata info to new summary data frame.
    summary._metadata = list(set(summary._metadata))
    summary._units = {}
    summary._descriptions = {}
    for key in summary.keys():
        summary[key]._units = data[0][key]._units
    for id_, _ in summary.iterrows():
        summary._units.update(data[id_]._units)
        summary._descriptions.update(data[id_]._descriptions)
        for section, metadata in data[id_].metadata.items():
            for key, info in metadata.items():
                if key in summary.keys():
                    summary[key][id_], summary[key]._units = info
                else:
                    summary[key] = info.value
                    summary[key]._units = info.unit

    return data, summary


def read(filepath_or_buffer, header=0, units=1, **kwargs):
    """Read experimental data into pandas DataFrame.

    Parameters
    ----------
    filepath_or_buffer : string or file handle / StringIO.

    header : int
        Row to use for the column labels of the parsed DataFrame.
    units : int
        Row to use for the unit properties of the parsed DataFrame.

    Returns
    -------
    result : pandas DataFrame

    """

    with open(filepath_or_buffer, 'r') as f:
        metadata = parse_metadata(f)
        result = parse_raw_data(f, **kwargs)

    result = append_metadata(result, metadata)

    # Currently, pandas only copies attributes that are added to
    # _metadata when it is copied.  Since pandas actually copies
    # frames frequently, this is a problem. To get around this, use
    # monkey-patching to store frame attributes and methods.
    result._metadata.append('_units')  # unit dictionary
    result._metadata.append('_descriptions')  # description dictionary
    result._metadata.append('_uncertainty')  # uncertainty dictionary
    result._metadata = list(set(result._metadata))

    return result


def parse_metadata(handle):
    """Parse test data file header metadata.

    Parameters
    ----------
    handle : test data file handle

    Returns
    -------
    metadata : dict
        parsed metadata dictionary describing test procedure

    """

    MetadataInfo = namedtuple('MetadataInfo', ['value', 'unit'])

    metadata = {}
    while True:
        line = handle.readline().strip()
        if line.startswith('[raw data]'):
            return metadata
        elif line.startswith('[uncertainty]'):
            metadata['uncertainty'] = parse_uncertainty(handle)
        elif line.startswith('[') and line.endswith(']'):
            section = cleanse_names(line.strip().strip('[]'))
            metadata[section] = {}
        else:
            key, info = [item.strip() for item in line.split('=')]
            key = cleanse_names(key)
            value, unit = parse_metadata_info(info)
            metadata[section][key] = MetadataInfo(*parse_metadata_info(info))


def parse_metadata_info(info):
    """Parse floating point metadata info.

    Parameters
    ----------
    info : string

    Returns
    -------
    value : float
    unit : string

    """

    value, _, unit = [item.strip() for item in info.partition('[')]
    unit = unit.strip('[]') if unit else None

    # TODO Not happy with this code, don't like logic trees in general.
    # Also, I think there is many opportunities for Exceptions, should
    # make this more robust.
    if unit:
        if casefold(unit) == 'bool':
            value = True if casefold(value) == 'true' else False
        elif value.isdigit():
            value = int(value)
        elif isdecimal(value.replace('.', '')):
            unit = parse_unit_string(unit)
            value = float(value)

    return value, unit


def parse_uncertainty(handle):
    """Parse the lines pertaining to the measurement uncertainty.

    Parameters
    ----------
    handle : file object
        File object whose position is the start of the uncertainty
        section in the experimental test file.

    Returns
    -------
    info : dict
        Dictionary containing measurement uncertainty information
        for the measurements defined in the experimental test file
        header.

    """

    line = handle.readline().strip()
    info = {}
    while not line.startswith('[') and not line.endswith(']'):
        line_start = handle.tell()
        key, uncer_info = parse_uncertainty_info(line)
        info[key] = uncer_info
        line = handle.readline().strip()
    handle.seek(line_start)

    return info


def parse_raw_data(handle, **kwargs):
    """Parse raw data from test output data file.

    Parameters
    ----------
    handle : test data file handle

    Returns
    -------
    result : pandas DataFrame

    """

    read_col_metadata = lambda line: line.strip().split(',')[1:]

    column_names = cleanse_names(read_col_metadata(handle.readline()))
    column_units = read_col_metadata(handle.readline())
    if 'parse_dates' in kwargs:
        parse_dates = kwargs['parse_dates']
        kwargs.popitem('parse_dates')
    else:
        parse_dates = True
    result = pd.read_csv(handle, names=column_names,
                         parse_dates=parse_dates, **kwargs)

    for key, unit in zip(result.keys(), column_units):
        result[key]._units = parse_unit_string(unit)
    result._units = {key: result[key]._units for key in result.keys()}

    result = translate_keys(result, result.keys())
    result._descriptions = {
        key: result[key]._descriptions for key in result.keys()
    }

    return result


def cleanse_names(names, bad_chars=[], repl='_'):
    """Cleanse a list of proposed column names to correct format.

    Parameters
    ----------
    names : string or [string]
        A string or list of proposed DataFrame column name strings
        usually read from test data file raw data header or metadata
        information.
    bad_chars : [string]
        List of invalid or bad characters that should be replaced from
        name strings if present
    repl : string
        String replacement for bad characters in cleansed name strings.

    Returns
    -------
    result : string or [string]
        String or list of cleansed DataFrame column names.

    Examples
    >>> cleanse_names(['a b c d', 'e_f g_i', 'j_k'])
    ['a_b_c_d', 'e_f_g_i', 'j_k']

    >>> cleanse_names(['1abc0'], repl='_')
    ['_abc0']

    >>> cleanse_names(' xxx')
    '_xxx'

    >>> cleanse_names('abcdef')
    'abcdef'

    """

    clean = lambda x, y: x + y if isidentifier(x + y) else x + repl

    result = ''
    if isinstance(names, str):
        for char in names:
            result = clean(result, char)
    else:
        result = [result] * len(names)
        for ind, name in enumerate(names):
            for char in name:
                result[ind] = clean(result[ind], char)

    return result


def append_metadata(data, metadata):
    """Append metadata information to the measurement DataFrame.

    Parameters
    ----------
    data : pandas DataFrame
        measurement DataFrame associated with metadata.
    metadata : dict
        metadata dictionary usually parsed from test data file header.

    Returns
    -------
    result : pandas DataFrame
        measurement DataFrame containing additional metadata properties.

    """

    data.metadata = metadata
    for section, meta in metadata.items():
        if section == 'uncertainty':
            data.__dict__['_uncertainty'] = meta
            for v in meta.values():
                v.units = {n: data.units(n) for n in v.names.values()}
        else:
            data.__dict__[section] = pd.DataFrame(
                {key: [info.value] for key, info in meta.items()}
            )
            for key, info in meta.items():
                data.__dict__[section][key]._units = info.unit

    return data
